### ISSUE TITLE
No playback devices are being detected 

### ISSUE THREAD

**Issue by Jolanrensen** [bezmi/addon-phlex#1]
"There was an error retrieving the list of devices, please try again later." is the only error I get every time when trying to find plex or cast devices to play on. Only once in a blue moon will it detect my Nvidia shield as player and thus get it to work. (might be because I'm running Hass.io on a raspberry pi zero, it's not that powerful, however before, when I was running raspian, it worked much better so it must be possible)

**Comment by bezmi** [comment]
Sorry, I don't have a Nvidia shield nor a pi zero to test with. Currently I'm running Hass.io on a pi 3 and it detects my chromecast and google home, as well as plex clients okay. 

Is your system able to detect web clients on plex at all?

**Comment by Jolanrensen** [comment]
Yes it works, but only sometimes. For example, just now I got Phlex to play music on my Shield from my google home (after having to re-link Google, because there was just an error before). So it's quite unstable, but it works sometimes, possibly because the zero is not that strong

**Comment by bezmi** [comment]
It might be the Pi or an issue with phlex. There's a whole section on the phlex readme for issues with casting. If you've got an available windows machine, could you test phlex under xampp to see if it picks up your shield then?

Aside from that, when I was experimenting with nginx,  there were issues similar to what you're describing but switching over to apache seemed to fix them for me.

There is also an experimental toggle in the 'plex' tab in the settings menu which might have some effect. I'm not familiar with the actual Phlex code so that's about as far as I can help unfortunately.

**Comment by Jolanrensen** [comment]
I've used xampp before on my linux laptop which worked completely fine, but I couldn't leave it on all the time, so that's why I want to use the pi. It worked for a whole day yesterday! But when I tried it again today it lost the shield again :( (both devices are ethernet connected). I do think switching to apache improved the reliability though

**Comment by Jolanrensen** [comment]
Okay so it was basically the low strength of the pi zero that was to blame. I now have a pi 3 and it finds all devices immediately
